import type { PaletteLike } from "../modes/paletteTypes";

export const explorerColors = (
  palette: PaletteLike,
): Record<string, string> => ({
  foreground: palette.fg0,
  background: palette.bg0,
  "activityBar.background": palette.bg0,
  "activityBar.foreground": palette.fg1,
  "activityBar.inactiveForeground": palette.comment,
  "sideBar.background": palette.bg0,
  "sideBar.foreground": palette.fg1,
  "sideBarTitle.foreground": palette.fg0,
  "sideBarSectionHeader.background": palette.bg1,
  "sideBarSectionHeader.foreground": palette.fg1,
  "list.activeSelectionBackground": palette.bg2,
  "list.activeSelectionForeground": palette.fg0,
  "list.inactiveSelectionBackground": palette.bg1,
  "list.inactiveSelectionForeground": palette.fg1,
  "list.hoverBackground": palette.bg1,
  "list.hoverForeground": palette.fg0,
  "list.highlightForeground": palette.fg0,
  "list.errorForeground": palette.error,
  "list.warningForeground": palette.operator,
  "tree.indentGuidesStroke": palette.bg2,
  "statusBar.background": palette.bg1,
  "statusBar.foreground": palette.fg1,
  "statusBarItem.remoteBackground": palette.bg2,
  "statusBarItem.remoteForeground": palette.fg0,
  "titleBar.activeBackground": palette.bg0,
  "titleBar.activeForeground": palette.fg1,
  "titleBar.inactiveBackground": palette.bg0,
  "titleBar.inactiveForeground": palette.comment,
  "panel.background": palette.bg0,
  "panelTitle.activeForeground": palette.fg0,
  "panelTitle.inactiveForeground": palette.fg1,
});
